name: Terraform Pre-commit

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  precommit:
    runs-on: ubuntu-latest   # You can use windows-latest if needed
    
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Install dependencies
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0  # Specify your desired Terraform version

      # Install TFLint
      - name: Install TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          echo "/usr/local/bin" >> $GITHUB_ENV  # Correctly set PATH for future steps
        shell: bash

      # Install terraform-docs
      - name: Install terraform-docs
        run: |
          curl -Lo terraform-docs.tar.gz https://github.com/terraform-docs/terraform-docs/releases/download/v0.16.0/terraform-docs-v0.16.0-linux-amd64.tar.gz
          tar -xzf terraform-docs.tar.gz
          sudo mv terraform-docs /usr/local/bin/
        shell: bash

      # Install pre-commit
      - name: Install pre-commit
        run: |
          pip install pre-commit
        shell: bash

      # Run pre-commit hooks
      - name: Run pre-commit
        run: |
          pre-commit run --all-files



